/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class SPlayerMpris {
  constructor()
  registerEventHandler(callback: (event: MprisEvent) => void): void
  setPlaybackStatus(status: string): void
  setMetadata(info: TrackInfo): void
  setPosition(pos: number): void
  setLoopStatus(status: string): void
  setVolume(volume: number): void
  setProgress(pos: number, length: number): void
}

export interface MprisEvent {
  eventType: string
  value?: number
}

export interface TrackInfo {
  title?: string
  artist?: string
  album?: string
  length?: number
  url?: string
}
