[workspace]
members = [
  "native/external-media-integration",
  "native/ferrous-opencc-wasm",
  "native/linux-portal",
  "native/taskbar-lyric",
  "native/tools",
  "native/audio-capture",
]

resolver = "3"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
strip = true
panic = "abort"
