packages:
  - "."
  - "native/external-media-integration"
  - "native/ferrous-opencc-wasm"
  - "native/taskbar-lyric"
  - "native/tools"

blockExoticSubdeps: false

allowBuilds:
  "@applemusic-like-lyrics/core": true
  "@applemusic-like-lyrics/lyric": true
  "@parcel/watcher": true
  better-sqlite3: true
  core-js: true
  electron: true
  electron-winstaller: true
  esbuild: true
  sharp: true
  vue-demi: true
  register-scheme: false
  wasm-pack: false

minimumReleaseAgeExclude:
  - "@neteasecloudmusicapienhanced/api"
  - better-sqlite3@13.0.1
