/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * 全局快捷键管理器
 *
 * 通过 XDG Desktop Portal 注册全局快捷键，绕过 Electron 的 `globalShortcut`
 */
export declare class GlobalShortcuts {
  /**
   * 创建全局快捷键管理器
   *
   * 会启动一个后台线程运行 D-Bus 事件循环，`bind` 之后快捷键激活时通过回调通知
   */
  constructor(callback: (event: ShortcutActivatedEvent) => void)
  /**
   * 当前环境下 portal 是否可用（接口存在且版本 >= 1）
   *
   * 探测在后台线程的常驻 runtime 上执行。注意不能用临时 runtime：
   * ashpd 会把 D-Bus 连接缓存在静态变量里，临时 runtime 销毁后缓存连接随之失效，
   * 后续所有 portal 调用都会永久挂起
   */
  isSupported(): Promise<boolean>
  /**
   * 创建会话并绑定快捷键
   *
   * 会弹出系统确认窗口，返回用户拒绝绑定或未绑定成功的快捷键 ID 列表，
   * 全部成功时返回空数组
   */
  bind(shortcuts: Array<ShortcutDescriptor>): Promise<Array<string>>
  /** 关闭会话，解绑全部快捷键 */
  unbind(): Promise<void>
  /**
   * 请求桌面环境打开快捷键配置界面
   *
   * portal 模式下应用内无法自定义快捷键，只能由用户在系统设置中修改。
   * 需要已经 `bind` 成功建立会话，否则会返回错误
   */
  configure(): Promise<void>
  /**
   * 停止后台线程，释放资源
   *
   * 应在应用退出时调用，调用后不应再使用该实例
   */
  dispose(): void
}
export type NapiGlobalShortcuts = GlobalShortcuts

/** 快捷键激活事件（通过 JS 回调派发） */
export interface ShortcutActivatedEvent {
  /** 应用内快捷键 ID */
  shortcutId: string
  /** 触发时间戳（毫秒） */
  timestamp: number
}

/** 单个快捷键描述 */
export interface ShortcutDescriptor {
  /** 应用内唯一 ID，用于识别触发的是哪个快捷键 */
  id: string
  /** 用户可读的描述文本，会显示在系统确认弹窗中 */
  description: string
  /** Electron 格式的推荐触发键（如 "CmdOrCtrl+Shift+M"），可为空（不传推荐键） */
  preferShortcut?: string
}
